apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  containers:
    - name: worker
      image: imageprocessing/worker:latest
      imagePullPolicy: Never
      env:
        - name: STORAGE_DATA_DIR
          value: /data/imageprocessing
        - name: HF_HOME
          value: /home/appuser/.cache/huggingface
        - name: U2NET_HOME
          value: /home/appuser/.u2net
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "10.244.0.115:9092"
        - name: JOB_REQUESTS_TOPIC
          value: "job.requests"
        - name: JOB_RESULTS_TOPIC
          value: "job.results"
      volumeMounts:
        - mountPath: "/home/appuser/.cache/huggingface"
          name: model-cache
        - mountPath: "/home/appuser/.u2net"
          name: rembg-cache
        - mountPath: "/data/imageprocessing"
          name: shared-storage
  volumes:
    - name: model-cache
      emptyDir: {}
    - name: rembg-cache
      emptyDir: {}
    - name: shared-storage
      emptyDir: {}
