apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: imageprocessing
  labels:
    app: keycloak
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        layer: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      initContainers:
        - name: wait-for-keycloak-db
          image: postgres:18-alpine
          envFrom:
            - secretRef:
                name: keycloak-db-secret
          command:
            - sh
            - -c
            - >
              until pg_isready -h postgres -U "$KC_DB_USERNAME" -d keycloak; do
                echo "waiting for keycloak database...";
                sleep 2;
              done
      containers:
        - name: keycloak
          image: gitlab-edu.supsi.ch:5050/dti-isin/roberto.guidi/didattica/progetti-semestre-diploma/cloud-native-image-processing/keycloak:feature-53-update-gateway-to-handle-auth
          imagePullPolicy: Always
          args: ["start", "--import-realm"]
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-db-secret
            - secretRef:
                name: keycloak-admin-secret
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9000
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health/ready
              port: management
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: management
            initialDelaySeconds: 40
            periodSeconds: 10
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config
