apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak-destination
  namespace: {{ .Values.namespace }}
spec:
  host: keycloak
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 15s
