apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-storage
spec:
  storageClassName: manual
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/imageprocessing
