apiVersion: v1
kind: Pod
metadata:
  name: kafka
  namespace: imageprocessing
spec:
  containers:
    - name: kafka
      image: apache/kafka:3.9.0
      envFrom:
        - configMapRef:
            name: kafka-config
      ports:
        - containerPort: 9092
        - containerPort: 9093
      volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
      readinessProbe:
        exec:
          command: ["/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
        initialDelaySeconds: 15
        periodSeconds: 10
      livenessProbe:
        exec:
          command: ["/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
        initialDelaySeconds: 30
        periodSeconds: 20
  volumes:
    - name: kafka-data
      emptyDir: {} # VolumeClaimTemplate was used in Lecture 3
