apiVersion: v1
kind: Pod
metadata:
  name: orchestrator
  namespace: imageprocessing
spec:
  initContainers:
    - name: wait-for-postgres
      image: postgres:18-alpine
      imagePullPolicy: Never
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
      command:
      - sh
      - -c
      - |
        until pg_isready -h postgres -U $POSTGRES_USER -d $POSTGRES_DB; do
          echo "Waiting for postgres..."
          sleep 2
        done
  containers:
    - name: orchestrator
      image: imageprocessing/orchestrator:latest
      imagePullPolicy: Never
      envFrom:
        - configMapRef:
            name: orchestrator-config
      env:
        - name: POSTGRES_USER_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
      volumeMounts:
        - mountPath: "/data/imageprocessing"
          name: pvc-shared-storage
      readinessProbe:
        httpGet:
          path: /internal/actuator/health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /internal/actuator/health
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
  volumes:
    - name: pvc-shared-storage
      persistentVolumeClaim:
        claimName: pvc-shared-storage
