apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-storage
  namespace: imageprocessing
spec:
  storageClassName: manual
  volumeName: pv-shared-storage
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
