apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-model-cache
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storage.modelCache.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.modelCache.size | quote }}
