spring.application.name=cloud-native-image-processing
spring.datasource.url=jdbc:postgresql://localhost:5432/${postgres_db_name:cloud_native_db}
spring.datasource.username=${postgres_user_name}
spring.datasource.password=${postgres_user_password}
spring.jpa.hibernate.ddl-auto=update
