apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: imageprocessing/frontend:latest
      imagePullPolicy: Never
      env:
        - name: ORCHESTRATOR_URL
          value: http://orchestrator-service:8080/internal
