apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-model-cache
  namespace: imageprocessing
spec:
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
