apiVersion: v1
kind: Secret
metadata:
  name: gateway-oauth2-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: {{ .Values.keycloak.secret.client | quote }} 
