spring.application.name=gateway
server.port=8080
orchestrator.url=${ORCHESTRATOR_URL:http://localhost:8081/internal}
#spring.profiles.active=local

# --- OAuth2 / Keycloak (Gateway acts as BFF, Authorization Code flow) ---
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=${KEYCLOAK_CLIENT_ID:gateway}
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.provider.keycloak.authorization-uri=${KEYCLOAK_AUTHORIZATION_URI}
spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_TOKEN_URI}
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${KEYCLOAK_JWKS_URI}
spring.security.oauth2.client.provider.keycloak.user-info-uri=${KEYCLOAK_USERINFO_URI}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

keycloak.logout-uri=${KEYCLOAK_LOGOUT_URI}

# --- Kafka
kafka.topics.user-events=user.events
