apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator 
  namespace: imageprocessing
  labels:
    app: orchestrator  
    layer: backend
spec:
  replicas: 1 #(default: 1)
  minReadySeconds: 0 #(default: 0)
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app : orchestrator
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      initContainers:
        - name: wait-for-postgres
          image: postgres:18-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: orchestrator-config
                  key: POSTGRES_DB
          command:
          - sh
          - -c
          - |
            until pg_isready -h postgres -U $POSTGRES_USER -d $POSTGRES_DB; do
              echo "Waiting for postgres..."
              sleep 2
            done
      containers:
        - name: orchestrator
          image: gitlab-edu.supsi.ch:5050/dti-isin/roberto.guidi/didattica/progetti-semestre-diploma/cloud-native-image-processing/orchestrator:feature-53-update-gateway-to-handle-auth
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/data/imageprocessing"
              name: pvc-shared-storage
          readinessProbe:
            httpGet:
              path: /internal/actuator/health
              port: 8080
            initialDelaySeconds: 5  
            periodSeconds: 10        
            timeoutSeconds: 5        
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /internal/actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10        
            timeoutSeconds: 5        
            failureThreshold: 3
          env:
            - name: POSTGRES_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: orchestrator-config
      volumes:
        - name: pvc-shared-storage
          persistentVolumeClaim:
            claimName: pvc-shared-storage

