apiVersion: v1
kind: Service
metadata: 
  name: orchestrator-service
  namespace: imageprocessing
spec:
  selector:
    app: orchestrator 
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
