apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:18-alpine
    imagePullPolicy: Never
    env:
      - name: POSTGRES_DB
        value: cloud_native_db
      - name: POSTGRES_USER
        value: yourusername
      - name: POSTGRES_PASSWORD
        value: yourpassword
    volumeMounts:
      - name: postgres-data
        mountPath: /var/lib/postgresql
  volumes:
    - name: postgres-data
      emptyDir: {}
