apiVersion: v1
kind: Pod
metadata:
  name: orchestrator
spec:
  initContainers:
    - name: wait-for-postgres
      image: postgres:18-alpine
      imagePullPolicy: Never
      env:
        - name: POSTGRES_DB
          value: cloud_native_db
        - name: POSTGRES_USER
          value: yourusername
      command:
      - sh
      - -c
      - |
        until pg_isready -h 10.244.0.113 -U $POSTGRES_USER -d $POSTGRES_DB; do
          echo "Waiting for postgres..."
          sleep 2
        done
  containers:
    - name: orchestrator
      image: imageprocessing/orchestrator:latest
      imagePullPolicy: Never
      env:
        - name: POSTGRES_DB
          value: cloud_native_db
        - name: POSTGRES_HOST
          value: 10.244.0.113
        - name: STORAGE_DATA_DIR
          value: /data/imageprocessing
        - name: ORCHESTRATOR_PORT
          value: "8080"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "10.244.0.115:9092"
        - name: POSTGRES_USER_NAME
          value: yourusername
        - name: POSTGRES_USER_PASSWORD
          value: yourpassword
      volumeMounts:
        - mountPath: "/data/imageprocessing"
          name: shared-storage
  volumes:
    - name: shared-storage
      emptyDir: {}
