apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerConfigJson | quote }}
