apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-storage
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storage.sharedStorage.storageClassName | quote }}
  volumeName: pv-shared-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.sharedStorage.size | quote }}
