apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: imageprocessing
spec:
  containers:
    - name: postgres
      image: postgres:18-alpine
      imagePullPolicy: Never
      envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: postgres-config
