apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: imageprocessing
data:
  STORAGE_DATA_DIR: /data/imageprocessing
  LOCAL_DATA_DIR: /tmp/imageprocessing/data
  HF_HOME: /home/appuser/.cache/huggingface
  U2NET_HOME: /home/appuser/.u2net
  WORKER_PORT: "8080"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  JOB_REQUESTS_TOPIC: "job.requests"
  JOB_RESULTS_TOPIC: "job.results"
  KAFKA_CONSUMER_GROUP: "ai-worker" 
