spring.application.name=orchestrator
spring.datasource.url=jdbc:postgresql://localhost:5432/${postgres_db_name:cloud_native_db}
spring.datasource.username=${postgres_user_name}
spring.datasource.password=${postgres_user_password}
spring.jpa.hibernate.ddl-auto=create
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1.0
logging.file.name=logs/image-processor.log
server.servlet.context-path=/internal
server.port=8081
worker.url=${worker_url}
spring.profiles.active=local
