spring.application.name=orchestrator
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB_NAME:cloud_native_db}
spring.datasource.username=${POSTGRES_USER_NAME}
spring.datasource.password=${POSTGRES_USER_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1.0
logging.file.name=logs/image-processor.log
server.servlet.context-path=/internal
server.port=${ORCHESTRATOR_PORT:8081}
worker.url=${WORKER_URL:http://localhost:8082}
#spring.profiles.active=local
