apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Values.namespace }}
data:
  KC_DB: "postgres"
  KC_DB_URL_HOST: {{ .Values.postgres.host | quote }}
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: "keycloak"
  KC_HOSTNAME: "http://{{ .Values.keycloak.externalHost }}"
  KC_HOSTNAME_STRICT: "false"
  KC_PROXY_HEADERS: "xforwarded"
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_USER_EVENTS_TOPIC: {{ .Values.kafka.userEventsTopic | quote }}
