apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KC_DB_USERNAME: {{ .Values.keycloak.secret.db.username | quote }}
  KC_DB_PASSWORD: {{ .Values.keycloak.secret.db.password | quote }}
