apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.keycloak.secret.admin.username | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.keycloak.secret.admin.password | quote }}

